import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="bg-gray-500 p-4 flex justify-between font-bold">
        <Link href="/"> Home </Link>
        <Link href="/posts"> Posts </Link>
        <Link href="/articles"> Articles </Link>

      </nav>
      {children}
      </body>
    </html>
  );
}
